#!/usr/bin/env python3
"""Детерминированный сабсеттинг символьных шрифтов forecast-new.

Фаза 3 (байты): NotoSansSymbols2.ttf = 1.2 МБ raw качается почти всегда
(глифы мажорных аспектов есть только в нём). Сабсетим три символьных шрифта
по кодпоинтам, которые реально используются (symbols.js) + фиксированные
диапазоны из плана, и отдаём woff2.

Источник кодпоинтов — app/scripts/extract-symbol-codepoints.cjs (единый с
guard-тестом). fonttools нужен ТОЛЬКО для этого офлайн-шага; в рантайме и в
тестах он не требуется — сабсеты и манифест покрытия коммитятся.

Запуск (из корня репозитория, интерпретатор с установленным fonttools+brotli):
    .venv/bin/python app/scripts/subset-symbol-fonts.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

REPO_ROOT = Path(__file__).resolve().parents[2]
FONTS_DIR = REPO_ROOT / "app" / "frontend" / "fonts"
EXTRACTOR = REPO_ROOT / "app" / "scripts" / "extract-symbol-codepoints.cjs"
MANIFEST = FONTS_DIR / "symbol-subset-coverage.json"

# (исходник .ttf, имя сабсета .woff2). Порядок = порядок в font-стеке.
FONTS = [
    ("Astronomicon.ttf", "Astronomicon.subset.woff2"),
    ("NotoSansSymbols.ttf", "NotoSansSymbols.subset.woff2"),
    ("NotoSansSymbols2.ttf", "NotoSansSymbols2.subset.woff2"),
]


def load_codepoints(mode: str) -> list[int]:
    out = subprocess.run(
        ["node", str(EXTRACTOR), mode],
        capture_output=True,
        text=True,
        check=True,
    )
    return sorted(int(h, 16) for h in json.loads(out.stdout))


def cmap_codepoints(font: TTFont) -> set[int]:
    covered: set[int] = set()
    for table in font["cmap"].tables:
        covered.update(table.cmap.keys())
    return covered


def subset_font(src: Path, dst: Path, unicodes: list[int]) -> set[int]:
    options = subset.Options()
    options.flavor = "woff2"
    options.desubroutinize = True
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_bounds = True
    options.ignore_missing_unicodes = True

    font = subset.load_font(str(src), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    subset.save_font(font, str(dst), options)

    check = TTFont(str(dst))
    covered = cmap_codepoints(check)
    check.close()
    font.close()
    return covered


def main() -> int:
    unicodes = load_codepoints("subset")
    required = load_codepoints("required")
    covered_union: set[int] = set()
    original_union: set[int] = set()
    report = []

    for src_name, dst_name in FONTS:
        src = FONTS_DIR / src_name
        dst = FONTS_DIR / dst_name
        original_union |= cmap_codepoints(TTFont(str(src)))
        covered = subset_font(src, dst, unicodes)
        covered_union |= covered
        report.append(
            {
                "source": src_name,
                "subset": dst_name,
                "sourceBytes": src.stat().st_size,
                "subsetBytes": dst.stat().st_size,
                "glyphsCovered": len(covered),
            }
        )
        print(
            f"{src_name}: {src.stat().st_size:>9,} → {dst_name}: "
            f"{dst.stat().st_size:>7,} bytes ({len(covered)} glyphs)"
        )

    # Кодпоинты из symbols.js, которые исходные шрифты реально отдавали локально.
    # Только их guard-тест обязан видеть покрытыми сабсетом; остальные (например
    # ⊗ U+2297, ⊥ U+22A5, ⋔ U+22D4) исторически рендерятся системным шрифтом.
    served_locally = sorted(cp for cp in required if cp in original_union)
    fallback = sorted(cp for cp in required if cp not in original_union)

    manifest = {
        "note": "Auto-generated by app/scripts/subset-symbol-fonts.py — do not edit by hand.",
        "requestedCodepoints": [f"{cp:04X}" for cp in unicodes],
        "covered": sorted(f"{cp:04X}" for cp in covered_union),
        "servedLocally": [f"{cp:04X}" for cp in served_locally],
        "systemFallback": [f"{cp:04X}" for cp in fallback],
        "fonts": report,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=True) + "\n", "utf8")
    print(f"Wrote coverage manifest: {MANIFEST.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
